---
firewall_allowed_tcp_ports:
        - 22
        - 111
        - 24007
        - 24009
        - 24010
        - 49152
        - 49153
        - 38465
        - 38466
firewall_allowed_udp_ports:
        - 111

# Gluster config
gluster_mount_dir: /mnt/gluster
gluster_brick_dir: /srv/gluster/brick
gluster_brick_name: gluster
